#!/bin/bash
echo Dropping db...
sudo -u postgres dropdb otpprofiler
echo Creating db...
sudo -u postgres createdb -O abyrd otpprofiler
echo Applying schema...
psql -d otpprofiler -f ../OTPProfiler/schema.sql
echo Generating endpoints...
java -cp ../OpenTripPlanner/opentripplanner-graph-builder/target/graph-builder.jar org.opentripplanner.graph_builder.GraphStats --graph /var/otp/graphs/arbor/Graph.obj -o endpoints_random.csv endpoints -n 600
echo Populating request parameters and endpoints tables...
python ./populate_db.py

